// Phase 4: admin device tokens and FCM push notifications, against the LOCAL Supabase stack.
//
//   node scripts/setup-local.mjs --sink http://host.docker.internal:8799/ --fake-fcm http://host.docker.internal:8798
//   npx supabase functions serve --env-file supabase/functions/.env --no-verify-jwt
//   node --test --test-concurrency=1 tests/*.test.mjs
//
// The real push code runs end to end. Only Firebase itself is replaced by a local fake FCM server (this file starts it
// on port 8798) and a throw-away service account generated by setup-local.mjs, so NO real credentials are involved and
// these tests do not prove delivery through Google's servers; they prove what AXE sends, to whom, and what it does
// when FCM misbehaves. Synthetic data only.

import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { createHash, createPublicKey, randomBytes, verify } from "node:crypto";
import { createServer } from "node:http";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { deflateSync } from "node:zlib";

const v2 = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const config = JSON.parse(readFileSync(join(v2, "config", "server.json"), "utf8"));
const admin = JSON.parse(readFileSync(join(v2, "secrets", "local-admin.json"), "utf8"));
const env = readFileSync(join(v2, "backend", "supabase", "functions", ".env"), "utf8");
const envValue = (key) => env.match(new RegExp(`^${key}=(.*)$`, "m"))?.[1] ?? "";
const base = `${config.functionsUrl}/access`;
const adminBase = `${config.functionsUrl}/admin`;
const headers = { apikey: config.anonKey, Authorization: `Bearer ${config.anonKey}`, "Content-Type": "application/json" };

const device = () => createHash("sha256").update(randomBytes(32)).digest("hex");
const token = (prefix = "t-") => `${prefix}${randomBytes(14).toString("hex")}`; // >= 20 chars like a real FCM token
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function call(method, url, body, extra = {}) {
  const res = await fetch(url, { method, headers: { ...headers, ...extra }, body: body === undefined ? undefined : JSON.stringify(body) });
  const text = await res.text();
  return { status: res.status, body: text ? JSON.parse(text) : null };
}
const asAdmin = (accessToken) => (method, path, body) => call(method, `${adminBase}${path}`, body, { Authorization: `Bearer ${accessToken}` });

async function login(email, password) {
  const res = await fetch(`${admin.apiUrl}/auth/v1/token?grant_type=password`, {
    method: "POST", headers: { apikey: config.anonKey, "Content-Type": "application/json" }, body: JSON.stringify({ email, password }),
  });
  assert.equal(res.status, 200, `login ${email}`);
  return (await res.json()).access_token;
}

async function userId(accessToken) {
  const res = await fetch(`${admin.apiUrl}/auth/v1/user`, { headers: { apikey: config.anonKey, Authorization: `Bearer ${accessToken}` } });
  return (await res.json()).id;
}

// ---- service-role access, fetched from the Supabase CLI at run time (never written to disk) ---------------------
let svc;
function service() {
  if (!svc) {
    const st = JSON.parse(execFileSync("npx", ["--yes", "supabase", "status", "-o", "json"], {
      cwd: join(v2, "backend"), encoding: "utf8", shell: true, stdio: ["ignore", "pipe", "ignore"],
    }));
    svc = { url: st.API_URL, key: st.SERVICE_ROLE_KEY };
  }
  return svc;
}
const sh = () => ({ apikey: service().key, Authorization: `Bearer ${service().key}`, "Content-Type": "application/json" });
async function rows(table, filter) {
  const res = await fetch(`${service().url}/rest/v1/${table}?${filter}&select=*`, { headers: sh() });
  assert.equal(res.status, 200, `reading ${table}`);
  return res.json();
}
const deviceRows = (userIdValue) => rows("admin_devices", `user_id=eq.${userIdValue}&order=updated_at.desc`);
async function clearDevices() {
  const res = await fetch(`${service().url}/rest/v1/admin_devices?token=not.is.null`, { method: "DELETE", headers: sh() });
  assert.ok(res.status < 300, "clearing admin_devices");
}

async function waitFor(condition, what, ms = 8000) {
  const end = Date.now() + ms;
  while (Date.now() < end) {
    const value = await condition();
    if (value) return value;
    await sleep(100);
  }
  assert.fail(`timed out waiting for ${what}`);
}

// ---- a local fake of Firebase Cloud Messaging ------------------------------------------------------------------------
const sent = []; // every message the server tried to send
const oauthCalls = [];
let oauthFails = false;
let fcm;

function startFakeFcm() {
  fcm = createServer((req, res) => {
    let data = "";
    req.on("data", (c) => (data += c));
    req.on("end", () => {
      const reply = (code, body) => { res.statusCode = code; res.setHeader("Content-Type", "application/json"); res.end(JSON.stringify(body)); };
      if (req.url === "/token") {
        oauthCalls.push(Object.fromEntries(new URLSearchParams(data)));
        if (oauthFails) return reply(500, { error: "backend_error" });
        return reply(200, { access_token: "fake-access-token", expires_in: 61 }); // 61 s: the sender refreshes almost every time
      }
      const match = req.url?.match(/^\/v1\/projects\/([^/]+)\/messages:send$/);
      if (!match) return reply(404, {});
      const body = JSON.parse(data);
      sent.push({ project: match[1], authorization: req.headers.authorization, body });
      const t = body.message.token;
      if (t.startsWith("stale-notfound-")) return reply(404, { error: { code: 404, status: "NOT_FOUND", message: "Requested entity was not found.", details: [{ errorCode: "UNREGISTERED" }] } });
      if (t.startsWith("bad-token-")) return reply(400, { error: { code: 400, status: "INVALID_ARGUMENT", message: "The registration token is not a valid FCM registration token" } });
      if (t.startsWith("bad-payload-")) return reply(400, { error: { code: 400, status: "INVALID_ARGUMENT", message: "Invalid JSON payload received." } });
      if (t.startsWith("fail500-")) return reply(500, { error: { code: 500, status: "INTERNAL", message: "Internal error." } });
      return reply(200, { name: `projects/${match[1]}/messages/${sent.length}` });
    });
  });
  return new Promise((r) => fcm.listen(8798, "0.0.0.0", r));
}

// ---- submit helpers ---------------------------------------------------------------------------------------------------
function testPng() {
  const crc = (buf) => { let c = ~0; for (const b of buf) { c ^= b; for (let k = 0; k < 8; k++) c = (c >>> 1) ^ (0xedb88320 & -(c & 1)); } return ~c >>> 0; };
  const chunk = (type, d) => { const t = Buffer.concat([Buffer.from(type), d]); const l = Buffer.alloc(4); l.writeUInt32BE(d.length); const c = Buffer.alloc(4); c.writeUInt32BE(crc(t)); return Buffer.concat([l, t, c]); };
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(1, 0); ihdr.writeUInt32BE(1, 4); ihdr[8] = 8; ihdr[9] = 2;
  return Buffer.concat([Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]), chunk("IHDR", ihdr), chunk("IDAT", deflateSync(Buffer.from([0, 255, 0, 0]))), chunk("IEND", Buffer.alloc(0))]);
}
const PAYER = "Test Push Payer";
const INVITEE = "Test Push Invitee";
const submitPayment = (utr = `PUSH${Date.now()}${randomBytes(3).toString("hex")}`) => call("POST", `${base}/requests`, {
  kind: "payment", name: PAYER, plan: "5h", amountPaid: 199, utr, device: device(),
  screenshot: { type: "image/png", data: testPng().toString("base64") },
}).then((r) => ({ ...r, utr }));
const submitInvite = () => {
  const code = envValue("AXE_INVITE_CODES").split(",")[0].trim();
  return call("POST", `${base}/requests`, { kind: "invite", name: INVITEE, plan: "1h", code, device: device() }).then((r) => ({ ...r, code }));
};
const messagesFor = (requestId) => sent.filter((m) => m.body.message.data?.requestId === requestId);

let adminToken;
let adminId;
let second; // a second admin account, created for ownership tests and removed afterwards

before(async () => {
  assert.ok(envValue("FCM_SERVICE_ACCOUNT_JSON"), "run setup-local.mjs with --fake-fcm first (see the header of this file)");
  assert.match(envValue("AXE_FCM_API_BASE"), /8798/, "the functions must point at the fake FCM server");
  await startFakeFcm();
  adminToken = await login(admin.email, admin.password);
  adminId = await userId(adminToken);

  // A second admin (throw-away account) to prove that tokens have an owner.
  const email = `push-test-${randomBytes(4).toString("hex")}@axe.local`;
  const password = randomBytes(16).toString("base64url");
  const created = await fetch(`${service().url}/auth/v1/admin/users`, { method: "POST", headers: sh(), body: JSON.stringify({ email, password, email_confirm: true }) });
  assert.equal(created.status, 200, "creating the second test admin");
  const user = await created.json();
  const made = await fetch(`${service().url}/rest/v1/admins`, { method: "POST", headers: sh(), body: JSON.stringify({ user_id: user.id }) });
  assert.ok(made.status < 300, "making the second test user an admin");
  second = { id: user.id, token: await login(email, password) };
});

after(async () => {
  if (second) await fetch(`${service().url}/auth/v1/admin/users/${second.id}`, { method: "DELETE", headers: sh() });
  await clearDevices();
  fcm?.close();
});

// ---------------------------------------------------------------------------------------------------------------------
// Device token API
// ---------------------------------------------------------------------------------------------------------------------

test("tokens: registering needs an authenticated admin", async () => {
  const t = token();
  assert.equal((await call("POST", `${adminBase}/devices`, { token: t })).status, 401, "no session");
  assert.equal((await call("POST", `${adminBase}/devices`, { token: t }, { Authorization: "Bearer not-a-token" })).status, 401, "bad session");
  assert.equal((await call("DELETE", `${adminBase}/devices`, { token: t })).status, 401);
  assert.deepEqual(await rows("admin_devices", `token=eq.${t}`), [], "nothing was stored for an unauthenticated caller");
});

test("tokens: a registered token belongs to the authenticated admin, never to a client-supplied id", async () => {
  await clearDevices();
  const api = asAdmin(adminToken);
  const t = token();
  const res = await api("POST", "/devices", { token: t, user_id: second.id, userId: second.id, adminId: second.id });
  assert.equal(res.status, 200);
  const [row] = await rows("admin_devices", `token=eq.${t}`);
  assert.equal(row.user_id, adminId, "ownership comes from the session");
});

test("tokens: registering the same token again is idempotent and just refreshes it", async () => {
  await clearDevices();
  const api = asAdmin(adminToken);
  const t = token();
  await api("POST", "/devices", { token: t });
  const [first] = await rows("admin_devices", `token=eq.${t}`);
  await sleep(1100);
  await api("POST", "/devices", { token: t });
  const after = await rows("admin_devices", `token=eq.${t}`);
  assert.equal(after.length, 1, "no duplicate record");
  assert.ok(new Date(after[0].updated_at) > new Date(first.updated_at), "the registration time was refreshed");
});

test("tokens: rotation replaces the previous token of the same admin", async () => {
  await clearDevices();
  const api = asAdmin(adminToken);
  const oldToken = token();
  const newToken = token();
  await api("POST", "/devices", { token: oldToken });
  assert.equal((await api("POST", "/devices", { token: newToken, previousToken: oldToken })).status, 200);
  assert.deepEqual((await deviceRows(adminId)).map((r) => r.token), [newToken], "only the new token remains");
});

test("tokens: a previousToken belonging to another admin is never removed", async () => {
  await clearDevices();
  const theirs = token();
  await asAdmin(second.token)("POST", "/devices", { token: theirs });
  const mine = token();
  await asAdmin(adminToken)("POST", "/devices", { token: mine, previousToken: theirs });
  assert.equal((await rows("admin_devices", `token=eq.${theirs}`)).length, 1, "the other admin's token is untouched");
  assert.equal((await rows("admin_devices", `token=eq.${mine}`)).length, 1);
});

test("tokens: each admin keeps only their most recent devices, so records cannot accumulate", async () => {
  await clearDevices();
  const api = asAdmin(adminToken);
  const all = [];
  for (let i = 0; i < 8; i++) {
    const t = token();
    all.push(t);
    await api("POST", "/devices", { token: t });
    await sleep(30);
  }
  const kept = (await deviceRows(adminId)).map((r) => r.token);
  assert.equal(kept.length, 5, "capped at five devices");
  assert.deepEqual(kept.sort(), all.slice(3).sort(), "the five most recent survive");
});

test("tokens: signing out removes only the caller's own token; unknown tokens are harmless", async () => {
  await clearDevices();
  const mine = token();
  const theirs = token();
  await asAdmin(adminToken)("POST", "/devices", { token: mine });
  await asAdmin(second.token)("POST", "/devices", { token: theirs });

  assert.equal((await asAdmin(adminToken)("DELETE", "/devices", { token: theirs })).status, 200);
  assert.equal((await rows("admin_devices", `token=eq.${theirs}`)).length, 1, "another admin's token cannot be deleted");

  assert.equal((await asAdmin(adminToken)("DELETE", "/devices", { token: mine })).status, 200);
  assert.deepEqual(await rows("admin_devices", `token=eq.${mine}`), [], "own token removed");
  assert.equal((await asAdmin(adminToken)("DELETE", "/devices", { token: token() })).status, 200);
  assert.equal((await asAdmin(adminToken)("DELETE", "/devices", {})).status, 200);
});

test("tokens: invalid input is refused", async () => {
  const api = asAdmin(adminToken);
  for (const body of [{}, { token: "short" }, { token: 12345 }, { token: "x".repeat(4097) }, { token: token(), previousToken: 7 }, { token: token(), previousToken: "short" }]) {
    assert.equal((await api("POST", "/devices", body)).status, 400, JSON.stringify(body).slice(0, 60));
  }
});

// ---------------------------------------------------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------------------------------------------------

test("push: a new payment request notifies the admin device with minimal content only", async () => {
  await clearDevices();
  const t = token();
  await asAdmin(adminToken)("POST", "/devices", { token: t });

  const submitted = await submitPayment();
  assert.equal(submitted.status, 201, JSON.stringify(submitted.body));
  const { requestId } = submitted.body;
  const [m] = await waitFor(() => { const x = messagesFor(requestId); return x.length && x; }, "the payment push");

  assert.equal(m.project, "axe-local-fake");
  assert.equal(m.authorization, "Bearer fake-access-token", "sent with the OAuth token from the service account");
  const message = m.body.message;
  assert.equal(message.token, t);
  assert.deepEqual(message.notification, { title: "AXE Admin", body: "New payment request received. Tap to review." });
  assert.deepEqual(message.data, { type: "new_request", requestId });
  assert.equal(message.android.notification.channel_id, "axe_requests");
  assert.equal(message.android.notification.tag, requestId);

  // Nothing about the request or the requester may be in the push, anywhere.
  const everything = JSON.stringify(m.body);
  for (const secret of [PAYER, submitted.utr, "199", "₹", "screenshot", "image/png", "iVBOR"]) {
    assert.ok(!everything.includes(secret), `the push must not contain "${secret}"`);
  }
  assert.deepEqual(Object.keys(message.data).sort(), ["requestId", "type"], "the data payload is exactly {type, requestId}");
  assert.equal(messagesFor(requestId).length, 1, "one notification per device");
});

test("push: a new invitation request notifies with its own minimal text and no code", async () => {
  await clearDevices();
  const t = token();
  await asAdmin(adminToken)("POST", "/devices", { token: t });

  const submitted = await submitInvite();
  assert.equal(submitted.status, 201, JSON.stringify(submitted.body));
  const { requestId } = submitted.body;
  const [m] = await waitFor(() => { const x = messagesFor(requestId); return x.length && x; }, "the invitation push");

  assert.deepEqual(m.body.message.notification, { title: "AXE Admin", body: "New invitation request received. Tap to review." });
  assert.deepEqual(m.body.message.data, { type: "new_request", requestId });
  const everything = JSON.stringify(m.body);
  assert.ok(!everything.includes(INVITEE) && !everything.includes(submitted.code), "no name and no invitation code in the push");
});

test("push: the notification's request id leads to the real request through the authenticated admin API", async () => {
  await clearDevices();
  await asAdmin(adminToken)("POST", "/devices", { token: token() });
  const { body: { requestId } } = await submitPayment();
  await waitFor(() => messagesFor(requestId).length, "the push");

  const detail = await asAdmin(adminToken)("GET", `/requests/${requestId}`);
  assert.equal(detail.status, 200);
  assert.equal(detail.body.request.name, PAYER, "the app gets the authoritative data from the backend, not from the push");
  assert.equal((await call("GET", `${adminBase}/requests/${requestId}`)).status, 401, "and only with an admin session");
});

test("push: every registered device is notified once, even if a token is registered twice", async () => {
  await clearDevices();
  const a = token();
  const b = token();
  await asAdmin(adminToken)("POST", "/devices", { token: a });
  await asAdmin(adminToken)("POST", "/devices", { token: a });
  await asAdmin(adminToken)("POST", "/devices", { token: b });
  await asAdmin(second.token)("POST", "/devices", { token: token() }); // a second admin's phone is notified too

  const { body: { requestId } } = await submitInvite();
  await waitFor(() => messagesFor(requestId).length >= 3, "three device messages");
  await sleep(500);
  const tokens = messagesFor(requestId).map((m) => m.body.message.token);
  assert.equal(tokens.length, 3, "one message per distinct device");
  assert.equal(new Set(tokens).size, 3, "no device is notified twice");
  assert.ok(tokens.includes(a) && tokens.includes(b));
});

test("push: no registered device means no FCM call and the request is unaffected", async () => {
  await clearDevices();
  const before = sent.length;
  const res = await submitInvite();
  assert.equal(res.status, 201);
  await sleep(800);
  assert.equal(sent.length, before, "nothing is sent when nobody is registered");
});

test("push: an FCM outage or rejection never breaks request creation", async () => {
  await clearDevices();
  await asAdmin(adminToken)("POST", "/devices", { token: token("fail500-") });

  const res = await submitPayment();
  assert.equal(res.status, 201, "the request is accepted even though FCM answers 500");
  const { requestId, pollToken } = res.body;
  await waitFor(() => messagesFor(requestId).length, "the attempted push");

  const listed = await asAdmin(adminToken)("GET", "/requests");
  assert.ok(listed.body.requests.some((r) => r.id === requestId), "the admin can still find the request in the list");
  const [row] = await rows("access_requests", `id=eq.${requestId}`);
  assert.equal(row.status, "pending");
  assert.equal((await rows("admin_devices", `token=like.fail500-*`)).length, 1, "a transient FCM error does not delete the device");
  await call("DELETE", `${base}/requests/${requestId}`, null, { "x-poll-token": pollToken });
});

test("push: an FCM authentication failure never breaks request creation", async () => {
  await clearDevices();
  await asAdmin(adminToken)("POST", "/devices", { token: token() });
  oauthFails = true;
  try {
    await sleep(1500); // let any cached OAuth token expire (the fake issues 61 s tokens)
    const before = sent.length;
    const res = await submitInvite();
    assert.equal(res.status, 201, "the request is accepted even though the FCM credentials are refused");
    await sleep(1200);
    assert.equal(sent.length, before, "nothing could be sent");
    const listed = await asAdmin(adminToken)("GET", "/requests");
    assert.ok(listed.body.requests.some((r) => r.id === res.body.requestId));
  } finally {
    oauthFails = false;
  }
});

test("push: the service-account OAuth assertion is a correctly signed RS256 JWT", async () => {
  await clearDevices();
  await asAdmin(adminToken)("POST", "/devices", { token: token() });
  oauthCalls.length = 0;
  await sleep(1500);
  const { body: { requestId } } = await submitInvite();
  await waitFor(() => messagesFor(requestId).length, "the push");
  const call1 = oauthCalls.at(-1);
  assert.equal(call1.grant_type, "urn:ietf:params:oauth:grant-type:jwt-bearer");
  const [h, p, s] = call1.assertion.split(".");
  const publicKey = createPublicKey(JSON.parse(envValue("FCM_SERVICE_ACCOUNT_JSON")).private_key);
  assert.ok(verify("sha256", Buffer.from(`${h}.${p}`), publicKey, Buffer.from(s, "base64url")), "signature verifies with the service account's key");
  const claims = JSON.parse(Buffer.from(p, "base64url").toString());
  assert.equal(claims.scope, "https://www.googleapis.com/auth/firebase.messaging");
  assert.equal(claims.iss, "fake@axe-local-fake.iam.gserviceaccount.com");
  assert.equal(claims.exp - claims.iat, 3600);
});

test("push: stale tokens are removed, but payload errors and outages never delete working devices", async () => {
  await clearDevices();
  const stale = token("stale-notfound-");
  const invalid = token("bad-token-");
  const payloadProblem = token("bad-payload-");
  const outage = token("fail500-");
  const good = token();
  for (const t of [stale, invalid, payloadProblem, outage, good]) await asAdmin(adminToken)("POST", "/devices", { token: t });

  const { body: { requestId } } = await submitInvite();
  await waitFor(() => messagesFor(requestId).length >= 5, "all five device messages");
  await waitFor(async () => (await rows("admin_devices", `token=eq.${stale}`)).length === 0, "the stale token to be removed");
  await sleep(300);

  const left = (await deviceRows(adminId)).map((r) => r.token);
  assert.ok(!left.includes(stale), "UNREGISTERED (404) removes the token");
  assert.ok(!left.includes(invalid), "an invalid-token error (400) removes the token");
  assert.ok(left.includes(payloadProblem), "a 400 about the payload must not delete a valid device");
  assert.ok(left.includes(outage), "a 500 must not delete a device");
  assert.ok(left.includes(good), "a healthy device stays");
});

test("lifecycle: a notification is not request history: deciding still deletes everything", async () => {
  await clearDevices();
  await asAdmin(adminToken)("POST", "/devices", { token: token() });
  const res = await submitPayment();
  const { requestId, pollToken } = res.body;
  await waitFor(() => messagesFor(requestId).length, "the push");

  assert.equal((await asAdmin(adminToken)("POST", `/requests/${requestId}/decision`, { decision: "reject" })).status, 200);
  const [stub] = await rows("access_requests", `id=eq.${requestId}`);
  for (const f of ["name", "amount_paid", "utr", "invite_code", "screenshot_path"]) assert.equal(stub[f], null, f);
  await call("DELETE", `${base}/requests/${requestId}`, null, { "x-poll-token": pollToken });
  assert.deepEqual(await rows("access_requests", `id=eq.${requestId}`), []);

  // Opening the notification for a request that is gone is answered with "not found", never with stale data.
  assert.equal((await asAdmin(adminToken)("GET", `/requests/${requestId}`)).status, 404);
});
